-- Widoki

/*
+W_DOSTEPNOSC_TARYFY
+W_FAKTURA
+W_IDENTYFIKATOR
+W_JEDNOSTKA
+W_KARA
+W_KLIENT
+W_KLIENT_BIZNESOWY
+W_KOD
+W_KRAJ_PREFIX
+W_KRAJ
----W_KRAJ_KRAJ
+W_MIASTO
+W_ODSETKI
+W_PLATNOSC
+W_PREFIX
+W_REGION
+W_REGULY
+W_ROZLICZENIE
-----W_SIATKA--POMIJAM!
+W_SKALOWANIE
+W_STAWKA
+W_STREFA
+W_SZABLON_FAKTURY
+W_TARYFA
+W_TARYFA_KLIENTA
+W_TARYFA_USLUGA
???W_TYP_SIATKI
+W_TYP_URZADZENIA
+W_TYP_ZDARZENIA
+W_UMOWA
+W_USLUGA
+W_USLUGA_KLIENTA
+W_WYMIANA
-----W_ZDARZENIE
*/



CREATE OR REPLACE VIEW W_STAWKA AS
SELECT S.ID "IDENTYFIKATOR",
  S.nazwa
FROM STAWKA "S";

CREATE OR REPLACE VIEW W_STREFA AS
SELECT S.ID "IDENTYFIKATOR",
  S.nazwa
FROM STREFA "S";

CREATE OR REPLACE VIEW W_TARYFA AS
SELECT T.ID "IDENTYFIKATOR",
  T.nazwa,
  T.DATA_OD,
  T.DATA_DO
FROM TARYFA "T";

CREATE OR REPLACE VIEW W_TYP_SIATKI AS
SELECT T.ID "IDENTYFIKATOR",
  T.NAZWA,
  T.BOOL1,
  T.BOOL2,
  T.NUM1,
  T.NUM2,
  T.DEC1,
  T.DEC2,
  T.TIME1,
  T.TIME2,
  T.INTERVAL1,
  T.INTERVAL2,
  T.STRING1,
  T.STRING2
FROM TYP_SIATKI "T";

/* BRAK W_USLUGA_KLIENTA
CREATE OR REPLACE VIEW W_ZDARZENIE AS
SELECT Z.ID "IDENTYFIKATOR",
*/

--DOKONCZYC JAK BEDZIE W_TYP_SIATKI!!!!!!!!!!!
--CREATE OR REPLACE VIEW SIATKA AS
--SELECT S.ID AS "IDENTYFIKATOR",
--FROM SIATKA "S";

--CREATE OR REPLACE VIEW W_KRAJ_KRAJ AS
--SELECT * FROM KRAJ_KRAJ; DOKONCZYC JAK BEDZIE STREFA, STAWKA

CREATE OR REPLACE VIEW W_JEDNOSTKA AS
SELECT J.ID AS "IDENTYFIKATOR", 
  J.NAZWA 
FROM JEDNOSTKA "J";
CREATE OR REPLACE VIEW W_WYMIANA AS
SELECT W.ID AS "IDENTYFIKATOR",
  J.nazwa "JEDNOSTKA_1",
  W.WARTOSC1,
  W.WARTOSC2,
  W.DATA_OD,
  W.DATA_DO,
  JJ.NAZWA "JEDNOSTKA_2"
FROM WYMIANA "W"
JOIN W_JEDNOSTKA "J" ON W.JEDNOSTKA__ID=J.IDENTYFIKATOR
JOIN W_JEDNOSTKA "JJ" ON W.JEDNOSTKA__ID_2=JJ.IDENTYFIKATOR;


create or replace view W_KARA AS
SELECT ID AS IDENTYFIKATOR, 
  NAZWA, 
  KWOTA 
FROM KARA;


CREATE OR REPLACE VIEW W_PREFIX AS
SELECT P.ID AS "IDENTYFIKATOR", 
  P.PREFIX 
FROM PREFIX "P";


CREATE OR REPLACE VIEW W_KRAJ AS
SELECT K.ID "IDENTYFIKATOR", 
  P.PREFIX, 
  P.IDENTYFIKATOR "ID_PREFIXU", 
  K.nazwa, 
  K.WALUTA 
FROM KRAJ "K" 
JOIN W_PREFIX "P" ON K.PREFIX__ID=P.IDENTYFIKATOR;

CREATE OR REPLACE VIEW W_REGION AS
SELECT R.ID "IDENTYFIKATOR", 
W_KRAJ.NAZWA "KRAJ", 
R.NAZWA "REGION" 
FROM REGION "R" 
JOIN W_KRAJ ON W_KRAJ.IDENTYFIKATOR=R.KRAJ__ID;


CREATE OR REPLACE VIEW W_MIASTO AS
SELECT M.ID "IDENTYFIKATOR", 
  M.nazwa "NAZWA_MIASTA", 
  R.region, 
  R.kraj 
from miasto "M" 
join w_region "R" on M.region__id=R.IDENTYFIKATOR;

create or replace view W_ODSETKI AS
SELECT ID AS IDENTYFIKATOR, 
  NAZWA, 
  PROCENT 
FROM ODSETKI;



CREATE OR REPLACE VIEW W_KOD AS
SELECT kod.id as identyfikator, 
  KRAJ.NAZWA AS NAZWA_KRAJU, 
  REGION.NAZWA AS NAZWA_REGIONU, 
  MIASTO.NAZWA AS NAZWA_MIASTA, 
  KOD.KOD AS KOD_POCZTOWY 
FROM KOD 
JOIN MIASTO ON MIASTO__ID=MIASTO.ID 
JOIN REGION ON REGION__ID=REGION.ID 
JOIN KRAJ ON KRAJ__ID=KRAJ.ID;

CREATE OR REPLACE VIEW W_DOSTEPNOSC_TARYFY AS
SELECT D.ID AS "IDENTYFIKATOR", 
  W_KOD.KOD_POCZTOWY AS "KOD POCZTOWY", 
  T.NAZWA AS "TARYFA", 
  D.DATA_OD, 
  D.DATA_DO 
FROM DOSTEPNOSC_TARYFY "D" 
JOIN W_KOD ON D.KOD__ID=W_KOD.IDENTYFIKATOR 
JOIN TARYFA "T" ON D.TARYFA__ID=T.ID;

CREATE OR REPLACE VIEW W_KLIENT AS
SELECT k.ID AS IDENTYFIKATOR, 
  K.IMIE, 
  K.NAZWISKO, 
  w_kod.NAZWA_KRAJU "KRAJ", 
  w_kod.NAZWA_REGIONU "REGION", 
  w_kod.KOD_POCZTOWY, 
  w_kod.NAZWA_MIASTA "MIASTO",
  K.ULICA "ULICA", 
  K.NR_DOMU "NR_DOMU", 
  K.PESEL_NIP "PESEL", 
  K.DATA_OD, 
  K.DATA_DO, 
  K.KLIENT__ID_PIERWOTNY 
from KLIENT "K" 
JOIN w_kod on w_kod.identyfikator=K.kod__ID 
where "IMIE" IS NOT NULL 
AND "NAZWISKO" IS NOT NULL 
AND "NAZWA_FIRMY" IS NULL;

CREATE OR REPLACE VIEW W_KLIENT_BIZNESOWY AS
SELECT k.ID AS IDENTYFIKATOR, 
k.klient__id as "PODMIOT ZARZADZAJACY" , 
(SELECT KK.NAZWA_FIRMY FROM KLIENT "KK" WHERE ID=k.klient__id) AS "NAZWA ZARZADCY",
  K.NAZWA_FIRMY, 
  w_kod.NAZWA_KRAJU "KRAJ", 
  w_kod.NAZWA_REGIONU "REGION", 
  w_kod.KOD_POCZTOWY, 
  w_kod.NAZWA_MIASTA "MIASTO", 
  K.ULICA, 
  K.NR_DOMU, 
  K.PESEL_NIP "NIP", 
  K.DATA_OD, 
  K.DATA_DO, 
  K.KLIENT__ID_PIERWOTNY 
from KLIENT "K" 
JOIN w_kod on w_kod.identyfikator=K.kod__ID 
where "IMIE" IS NULL 
AND "NAZWISKO" IS NULL 
AND "NAZWA_FIRMY" IS NOT NULL;

CREATE OR REPLACE VIEW W_UMOWA AS
SELECT U.ID "IDENTYFIKATOR",
  K.NAZWA "NAZWA KARY",
  K.KWOTA "KWOTA KARY",
  O.NAZWA "NAZWA ODSETEK",
  O.PROCENT "OPROCENTOWANIE",
  U.DATA_OD,
  U.DATA_DO
FROM UMOWA "U"
JOIN W_KARA "K" ON K.IDENTYFIKATOR=U.KARA__ID
JOIN W_ODSETKI "O" ON O.IDENTYFIKATOR=U.ODSETKI__ID;


CREATE OR REPLACE VIEW W_KRAJ_PREFIX AS
SELECT KRAJ.NAZWA AS NAZWA_KRAJU,
  PREFIX.prefix AS KOD_KRAJU 
FROM KRAJ 
JOIN PREFIX ON KRAJ.prefix__id = PREFIX.id;

CREATE OR REPLACE view W_REGULY AS
SELECT R.ID AS "IDENTYFIKATOR",
  R.nazwa,
  R.A_POST,
  R.POST,
  R.A_PRE,
  R.PRE,
  R.poMIN
FROM REGULY "R";

CREATE OR REPLACE VIEW W_SKALOWANIE AS
SELECT S.ID AS "IDENTYFIKATOR",
  J.IDENTYFIKATOR "IDENTYFIKATOR_JEDNOSTKI",
  J.nazwa,
  S.WARTOSC1,
  S.WARTOSC2
FROM SKALOWANIE "S"
JOIN W_JEDNOSTKA "J" ON S.JEDNOSTKA__ID = J.IDENTYFIKATOR;

create or replace VIEW W_TYP_URZADZENIA AS 
SELECT ID AS IDENTYFIKATOR, 
  NAZWA 
FROM TYP_URZADZENIA;
CREATE OR REPLACE VIEW W_IDENTYFIKATOR AS
SELECT I.ID AS "IDENTYFIKATOR", 
  W_TYP_URZADZENIA.IDENTYFIKATOR "IDENTYFIKATOR_URZ", 
  W_TYP_URZADZENIA.nazwa "NAZWA_URZ",
  W_PREFIX.PREFIX,
  I.NUMER, 
  I.AKTYWNY 
FROM IDENTYFIKATOR "I" 
JOIN W_TYP_URZADZENIA ON W_TYP_URZADZENIA.IDENTYFIKATOR=I.TYP_URZADZENIA__ID 
JOIN W_PREFIX ON W_PREFIX.IDENTYFIKATOR=I.PREFIX__ID;

CREATE OR REPLACE VIEW W_TYP_ZDARZENIA AS
SELECT ID AS IDENTYFIKATOR, 
  NAZWA 
FROM TYP_ZDARZENIA;

CREATE OR REPLACE VIEW W_USLUGA AS
SELECT U.ID "IDENTYFIKATOR",
  TZ.NAZWA "TYP_ZDARZENIA",
  U.WYMIANA__ID "ID_WYMIANY",
  U.NAZWA,
  U.ilosc,
  U.AKTYWNA,
  U.DATA_OD, 
  U.DATA_DO,
  U.cena,
  U.NUMER,
  U.mnoznik,
  U.okres_dni,
  U.waznosc_dni,
  U.okres_miesiecy,
  U.waznosc_miesiecy,
  U.priorytet,
  U.SQL
FROM USLUGA "U"
JOIN W_TYP_ZDARZENIA "TZ" ON U.TYP_ZDARZENIA__ID=TZ.IDENTYFIKATOR;

CREATE OR REPLACE VIEW W_SZABLON_FAKTURY AS
SELECT S.ID "IDENTYFIKATOR",
  K.NAZWA "KRAJ",
  S.NAZWA,
  S.NAGLOWEK,
  S.TRESC,
  S.STOPKA,
  S.PODPIS,
  S.typ_klienta,
  S.SPRZEDAWCA,
  S.ODBIORCA,
  S.tabela_bilingowa,
  S.podsumowanie,
  S.ZBiorcza,
  S.termin_platnosci,
  S.LAYOUT,
  S.SQL
FROM SZABLON_FAKTURY "S"
JOIN W_KRAJ "K" ON S.KRAJ__ID=K.IDENTYFIKATOR;

CREATE OR REPLACE VIEW W_FAKTURA AS
SELECT F.ID AS "IDENTYFIKATOR", 
  K.IMIE, 
  K.NAZWISKO, 
  K.NAZWA_FIRMY,
  W_KOD.NAZWA_KRAJU, 
  W_KOD.NAZWA_REGIONU, 
  W_KOD.KOD_POCZTOWY,
  W_KOD.nazwa_miasta, 
  K.ULICA,
  K.NR_DOMU,
  K.PESEL_NIP,
  SZ.NAZWA, 
  to_char(F.data_wystawienia,'dd-mm-yyyy hh24:mi:ss') AS "DATA_WYSTAWIENIA", 
  F.KWOTA, 
  F.niedoplata, 
  F.ODSETKI, 
  F.zaplacona, 
  F.numer_faktury FROM FAKTURA "F" 
JOIN klient "K" on f.KLIENT__ID=K.ID
JOIN szablon_faktury "SZ" ON F.numer_faktury = SZ.ID
JOIN W_KOD ON W_KOD.identyfikator=K.KOD__ID;

CREATE OR REPLACE VIEW W_TARYFA_KLIENTA AS
SELECT T.ID "IDENTYFIKATOR",
  K.KOD_POCZTOWY,
  K.NAZWA_MIASTA,
  K.NAZWA_REGIONU,
  K.NAZWA_KRAJU,
  I.IDENTYFIKATOR_URZ,
  I.NAZWA_URZ,
  T.UMOWA__ID,
  TAR.NAZWA "NAZWA_TARYFY",
  TAR.DATA_OD "TARYFA_OD",
  TAR.DATA_DO "TARYFA_DO",
  KL.IMIE,
  KL.NAZWISKO,
  KL.NAZWA_FIRMY,
  KL.PESEL_NIP,
  KL.EMAIL,
  T.DATA_OD "TARYFA_KLIENTA_OD",
  T.DATA_DO "TARYFA_KLIENTA_DO",
  T.GRUPA_FAKTUR,
  T.OKRES_ROZLICZENIOWY
FROM TARYFA_KLIENTA "T"
JOIN W_KOD "K" ON K.IDENTYFIKATOR=T.KOD__ID
JOIN W_IDENTYFIKATOR "I" ON T.IDENTYFIKATOR__ID=I.IDENTYFIKATOR
JOIN W_TARYFA "TAR" ON T.TARYFA__ID=TAR.IDENTYFIKATOR
JOIN KLIENT "KL" ON KL.ID = T.KLIENT__ID;

CREATE OR REPLACE VIEW W_ROZLICZENIE AS
SELECT R.ID "IDENTYFIKATOR",
  TK.IMIE,
  TK.NAZWISKO,
  TK.NAZWA_FIRMY,
  TK.PESEL_NIP,
  TK.EMAIL,
  TK.KOD_POCZTOWY,
  TK.NAZWA_MIASTA,
  TK.NAZWA_REGIONU,
  TK.NAZWA_KRAJU,
  TK.IDENTYFIKATOR_URZ,
  TK.NAZWA_URZ,
  TK.UMOWA__ID,
  TK.NAZWA_TARYFY,
  TK.GRUPA_FAKTUR,
  TK.OKRES_ROZLICZENIOWY,
  F.KWOTA, 
  F.niedoplata, 
  F.ODSETKI, 
  F.zaplacona, 
  F.numer_faktury,
  R.DATA_OD,
  R.DATA_DO
FROM ROZLICZENIE "R"
JOIN W_FAKTURA "F" ON R.FAKTURA__ID = F.IDENTYFIKATOR
JOIN W_TARYFA_KLIENTA "TK" ON TK.IDENTYFIKATOR=R.TARYFA_KLIENTA__ID;

CREATE OR REPLACE VIEW W_PLATNOSC AS
SELECT P.ID AS "IDENTYFIKATOR", 
  K.IMIE,
  K.NAZWISKO,
  K.NAZWA_FIRMY,
  K.PESEL_NIP,
  P.KWOTA AS "KWOTA_PLATNOSCI" 
FROM PLATNOSC "P"
JOIN KLIENT "K" ON K.ID=P.KLIENT__ID;

CREATE OR REPLACE VIEW W_USLUGA_KLIENTA AS
SELECT U.ID "IDENTYFIKATOR",
  USL.NAZWA "NAZWA_USLUGI",
  TAR_K.NAZWA_TARYFY,
  U.DATA_OD,
  U.DATA_DO,
  U.POZOSTALO,
  U.WYKORZYSTANE,
  U.NUMER,
  U.mnoznik,
  U.AKTYWNA
FROM USLUGA_KLIENTA "U"
JOIN W_TARYFA_KLIENTA "TAR_K" ON U.TARYFA_KLIENTA__ID = TAR_K.IDENTYFIKATOR
JOIN W_USLUGA "USL" ON U.USLUGA__ID = USL.IDENTYFIKATOR;

CREATE OR REPLACE VIEW W_TARYFA_USLUGA AS
SELECT T.ID "IDENTYFIKATOR",
  U.NAZWA "NAZWA_USLUGI",
  TAR.NAZWA "NAZWA_TARYFY",
  T.DATA_OD,
  T.DATA_DO
FROM TARYFA_USLUGA "T" 
JOIN W_TARYFA "TAR" ON TAR.IDENTYFIKATOR = T.TARYFA__ID
JOIN W_USLUGA "U" ON U.IDENTYFIKATOR = T.USLUGA__ID;